//// <auto-generated />
//using System;

//namespace LiveScore.Shared.Models.Dtos
//{

//    public class TournamentStandings
//    {
//        public DateTime generated_at { get; set; }
//        public string schema { get; set; }
//        public Tournament tournament { get; set; }
//        public Season season { get; set; }
//        public Standing[] standings { get; set; }
//    }


//    public class Sport
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Category
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Current_Season
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string start_date { get; set; }
//        public string end_date { get; set; }
//        public string year { get; set; }
//    }

//    public class Season
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string start_date { get; set; }
//        public string end_date { get; set; }
//        public string year { get; set; }
//        public string tournament_id { get; set; }
//    }

//    public class Standing
//    {
//        public string tie_break_rule { get; set; }
//        public string type { get; set; }
//        public Group[] groups { get; set; }
//    }

//    public class Group
//    {
//        public string name { get; set; }
//        public string id { get; set; }
//        public Team_Standings[] team_standings { get; set; }
//    }

//    public class Team_Standings
//    {
//        public Team team { get; set; }
//        public int rank { get; set; }
//        public string current_outcome { get; set; }
//        public int played { get; set; }
//        public int win { get; set; }
//        public int draw { get; set; }
//        public int loss { get; set; }
//        public int goals_for { get; set; }
//        public int goals_against { get; set; }
//        public int goal_diff { get; set; }
//        public int points { get; set; }
//        public int change { get; set; }
//    }

//    public class Team
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }


//}
