//// <auto-generated />
//using System;

//namespace LiveScore.Shared.Models.Dtos
//{


//    public class TournamentInfo
//    {
//        public DateTime generated_at { get; set; }
//        public string schema { get; set; }
//        public Tournament tournament { get; set; }
//        public Season season { get; set; }
//        public Round round { get; set; }
//        public Season_Coverage_Info season_coverage_info { get; set; }
//        public Coverage_Info coverage_info { get; set; }
//        public Group[] groups { get; set; }
//    }

//    public class Tournament
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public Sport sport { get; set; }
//        public Category category { get; set; }
//        public Current_Season current_season { get; set; }
//    }

//    public class Sport
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Category
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Current_Season
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string start_date { get; set; }
//        public string end_date { get; set; }
//        public string year { get; set; }
//    }

//    public class Season
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string start_date { get; set; }
//        public string end_date { get; set; }
//        public string year { get; set; }
//        public string tournament_id { get; set; }
//    }

//    public class Round
//    {
//        public string type { get; set; }
//        public string name { get; set; }
//        public int cup_round_match_number { get; set; }
//        public int cup_round_matches { get; set; }
//    }

//    public class Season_Coverage_Info
//    {
//        public string season_id { get; set; }
//        public int scheduled { get; set; }
//        public int played { get; set; }
//        public string max_coverage_level { get; set; }
//        public int max_covered { get; set; }
//        public string min_coverage_level { get; set; }
//    }

//    public class Coverage_Info
//    {
//        public bool live_coverage { get; set; }
//    }

//    public class Group
//    {
//        public string name { get; set; }
//        public string id { get; set; }
//        public Team[] teams { get; set; }
//    }

//    public class Team
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country { get; set; }
//        public string country_code { get; set; }
//        public string abbreviation { get; set; }
//    }


//}
