// <auto-generated>
// Not implemented yet
// </auto-generated>
namespace LiveScore.Features.TVSchedule.ViewModels
{
    using Prism.Mvvm;

    public class TVScheduleViewModel : BindableBase
    {
    }
}