// <auto-generated>
// Odds functions are disabled
// </auto-generated>
using LiveScore.Core.Models.Odds;

namespace LiveScore.Soccer.Models.Odds
{
    public class OddsMovementEvent
    {
        public OddsMovementEvent(
            byte betTypeId,
            Bookmaker bookmaker,
            OddsMovement oddsMovement)
        {
            BetTypeId = betTypeId;
            Bookmaker = bookmaker;
            OddsMovement = oddsMovement;
        }

        public byte BetTypeId { get; private set; }

        public Bookmaker Bookmaker { get; private set; }

        public OddsMovement OddsMovement { get; private set; }
    }
}