//// <auto-generated />
//using System;

//namespace LiveScore.Shared.Models.Dtos
//{

//    public class TeamStatistic
//    {
//        public DateTime generated_at { get; set; }
//        public string schema { get; set; }
//        public Tournaments tournament { get; set; }
//        public Team team { get; set; }
//        public Team_Season_Coverage team_season_coverage { get; set; }
//        public Team_Statistics team_statistics { get; set; }
//        public Player_Statistics[] player_statistics { get; set; }
//        public Goaltime_Statistics goaltime_statistics { get; set; }
//    }

//    public class Tournaments
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public Sport sport { get; set; }
//        public Category category { get; set; }
//        public Current_Season current_season { get; set; }
//    }

//    public class Sport
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Category
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Current_Season
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string start_date { get; set; }
//        public string end_date { get; set; }
//        public string year { get; set; }
//    }

//    public class Team
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country { get; set; }
//        public string country_code { get; set; }
//        public Sport1 sport { get; set; }
//        public Category1 category { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Sport1
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Category1
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country_code { get; set; }
//    }

//    public class Team_Season_Coverage
//    {
//        public int scheduled { get; set; }
//        public int played { get; set; }
//        public int platinum { get; set; }
//    }

//    public class Team_Statistics
//    {
//        public int matches_played { get; set; }
//        public int matches_won { get; set; }
//        public string form { get; set; }
//        public Goal_Attempts goal_attempts { get; set; }
//        public Shots_On_Goal shots_on_goal { get; set; }
//        public Shots_Off_Goal shots_off_goal { get; set; }
//        public Corner_Kicks corner_kicks { get; set; }
//        public Ball_Possession ball_possession { get; set; }
//        public Shots_Blocked shots_blocked { get; set; }
//        public Cards_Given cards_given { get; set; }
//        public Free_Kicks free_kicks { get; set; }
//        public Offsides offsides { get; set; }
//        public Shots_On_Bar shots_on_bar { get; set; }
//        public Goals_By_Foot goals_by_foot { get; set; }
//        public Goals_By_Head goals_by_head { get; set; }
//        public Goals_Scored goals_scored { get; set; }
//        public Goals_Conceded goals_conceded { get; set; }
//    }

//    public class Goal_Attempts
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Shots_On_Goal
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Shots_Off_Goal
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Corner_Kicks
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Ball_Possession
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Shots_Blocked
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Cards_Given
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Free_Kicks
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Offsides
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Shots_On_Bar
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Goals_By_Foot
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Goals_By_Head
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Goals_Scored
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Goals_Conceded
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Goaltime_Statistics
//    {
//        public Scored scored { get; set; }
//        public Conceded conceded { get; set; }
//    }

//    public class Scored
//    {
//        public int total { get; set; }
//        public Period[] period { get; set; }
//    }

//    public class Period
//    {
//        public string name { get; set; }
//        public int value { get; set; }
//    }

//    public class Conceded
//    {
//        public int total { get; set; }
//        public Period1[] period { get; set; }
//    }

//    public class Period1
//    {
//        public string name { get; set; }
//        public int value { get; set; }
//    }

//    public class Player_Statistics
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public int matches_played { get; set; }
//        public Statistics statistics { get; set; }
//        public int minutes_played { get; set; }
//    }

//    public class Statistics
//    {
//        public Goals_Scored1 goals_scored { get; set; }
//        public Offsides1 offsides { get; set; }
//        public Corner_Kicks1 corner_kicks { get; set; }
//        public Shots_On_Goal1 shots_on_goal { get; set; }
//        public Shots_Off_Goal1 shots_off_goal { get; set; }
//        public Shots_Blocked1 shots_blocked { get; set; }
//        public Assists assists { get; set; }
//        public Substituted_In substituted_in { get; set; }
//        public Substituted_Out substituted_out { get; set; }
//        public Goal_Attempts1 goal_attempts { get; set; }
//        public Interceptions interceptions { get; set; }
//        public Chances_Created chances_created { get; set; }
//        public Crosses crosses { get; set; }
//        public Passes_Short passes_short { get; set; }
//        public Passes_Medium passes_medium { get; set; }
//        public Passes_Long passes_long { get; set; }
//        public Duels_Header duels_header { get; set; }
//        public Duels_Sprint duels_sprint { get; set; }
//        public Duels_Tackle duels_tackle { get; set; }
//        public Goals_Conceded1 goals_conceded { get; set; }
//        public Clean_Sheets clean_sheets { get; set; }
//        public Performance_Score performance_score { get; set; }
//        public Cards_Given1 cards_given { get; set; }
//        public Goals_By_Head1 goals_by_head { get; set; }
//        public Goal_Line_Clearances goal_line_clearances { get; set; }
//        public Shots_Faced shots_faced { get; set; }
//        public Penalties_Faced penalties_faced { get; set; }
//    }

//    public class Goals_Scored1
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Offsides1
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Corner_Kicks1
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Shots_On_Goal1
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Shots_Off_Goal1
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Shots_Blocked1
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Assists
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Substituted_In
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Substituted_Out
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Goal_Attempts1
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Interceptions
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Chances_Created
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Crosses
//    {
//        public int total { get; set; }
//        public int successful { get; set; }
//        public int matches { get; set; }
//    }

//    public class Passes_Short
//    {
//        public int total { get; set; }
//        public int successful { get; set; }
//        public int matches { get; set; }
//    }

//    public class Passes_Medium
//    {
//        public int total { get; set; }
//        public int successful { get; set; }
//        public int matches { get; set; }
//    }

//    public class Passes_Long
//    {
//        public int total { get; set; }
//        public int successful { get; set; }
//        public int matches { get; set; }
//    }

//    public class Duels_Header
//    {
//        public int total { get; set; }
//        public int successful { get; set; }
//        public int matches { get; set; }
//    }

//    public class Duels_Sprint
//    {
//        public int total { get; set; }
//        public int successful { get; set; }
//        public int matches { get; set; }
//    }

//    public class Duels_Tackle
//    {
//        public int total { get; set; }
//        public int successful { get; set; }
//        public int matches { get; set; }
//    }

//    public class Goals_Conceded1
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Clean_Sheets
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Performance_Score
//    {
//        public float average { get; set; }
//        public int matches { get; set; }
//    }

//    public class Cards_Given1
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Goals_By_Head1
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Goal_Line_Clearances
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Shots_Faced
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }

//    public class Penalties_Faced
//    {
//        public int total { get; set; }
//        public int matches { get; set; }
//    }



//}
