// <auto-generated>
// </auto-generated>
namespace LiveScore.iOS.Services
{
    using LiveScore.Core.Services;
    using System;
    using System.Threading;
    using System.Threading.Tasks;
    using UIKit;

    public class BackgroundService
    {
        private CancellationTokenSource cancellationTokenSource;

        public async Task Start(IBackgroundJob job)
        {
            cancellationTokenSource = new CancellationTokenSource();
            var taskId = UIApplication.SharedApplication.BeginBackgroundTask("BackgroundService", OnExpiration);

            try
            {
                await job.Start(cancellationTokenSource.Token);
            }
            catch (OperationCanceledException ex)
            {
                // Write log
            }

            UIApplication.SharedApplication.EndBackgroundTask(taskId);
        }

        public void Stop()
        {
            cancellationTokenSource.Cancel();
        }

        private void OnExpiration()
        {
            cancellationTokenSource.Cancel();
        }
    }
}