// <auto-generated />

using System.Collections.Generic;
using System.Text;

namespace LiveScore.Soccer.ViewModels.Matches.MatchDetails.TrackerCommentary
{
    public static class TrackerWidgetHtml
    {
        private static readonly string StaticContent = BuildStaticContent();
        private static readonly string DynamicContent = BuildDynamicContent();

        public static string Generate(IDictionary<string, string> replaceValues)
        {
            var secondContent = DynamicContent;
            foreach (var keyValue in replaceValues)
            {
                secondContent = secondContent.Replace(keyValue.Key, keyValue.Value);
            }

            return StaticContent + secondContent;
        }

        private static string BuildStaticContent()
        {
            var builder = new StringBuilder();
            builder.Append("<!DOCTYPE HTML>");
            builder.Append("<html>");
            builder.Append("    <head>");
            builder.Append("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />" +
                                    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
            builder.Append("        <title>");
            builder.Append("            Live SoccerMatch Tracker");
            builder.Append("        </title>");
            builder.Append("       ");
            builder.Append("        <style>");
            builder.Append("            body {");
            builder.Append("                display: flex;");
            builder.Append("                justify-content: center;");
            builder.Append("                background-color: #161719 !important;");
            builder.Append("                overflow: hidden;");
            builder.Append("            }");
            builder.Append("            .widgets {");
            builder.Append("                max-width: 620px;");
            builder.Append("                width: 100%;");
            builder.Append("            }");
            builder.Append("            .sr-widget {");
            builder.Append("                border: rgba(0,0,0,0.12) solid 1px;");
            builder.Append("                margin-bottom: 24px;");
            builder.Append("            }");
            
            builder.Append(" /*");
            builder.Append("Using formula solid");
            builder.Append("$primary: #FF0000;");
            builder.Append("$home: #3f3f41;");
            builder.Append("$away: #9c9c9c;");
            builder.Append("$cl: #000000;");
            builder.Append("$base: #FFFFFF;");
            builder.Append("*/");
            builder.Append("/*");
            builder.Append("    Enable dark or light logo based on base color");
            builder.Append("*/");
            builder.Append("@import url(\"//fonts.googleapis.com/css?family=Roboto:300,400,500,700,900&subset=latin,latin-ext\");");
            builder.Append(".sr-bb {");
            builder.Append("  font-family: \"Roboto\", \"Noto\", \"Helvetica Neue\", \"Helvetica\", \"Arial\", sans-serif;");
            builder.Append("  background: #202124;");
            builder.Append("}");
            
            builder.Append(".sr-bb .sr-bb {");
            builder.Append("  background: none;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-win {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: red;");
            builder.Append("  border-color: red;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-draw {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #c2c2c2;");
            builder.Append("  border-color: #c2c2c2;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-lose {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #ff8787;");
            builder.Append("  border-color: #ff8787;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-2 {");
            builder.Append("  background-color: #e6e6e6;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-hoverable:hover {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #FF0000;");
            builder.Append("  border-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-home-1 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #3f3f41;");
            builder.Append("  border-color: #3f3f41;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-away-1 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #9c9c9c;");
            builder.Append("  border-color: #9c9c9c;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-home-2 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #3f3f41;");
            builder.Append("  border-color: #940000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-away-2 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #9c9c9c;");
            builder.Append("  border-color: #940000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-home-3 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #3f3f41;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-away-3 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #9c9c9c;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-home-4 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #79797a;");
            builder.Append("  border-color: #79797a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-away-4 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #bababa;");
            builder.Append("  border-color: #bababa;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-home-5 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #29292a;");
            builder.Append("  border-color: #29292a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-away-5 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #656565;");
            builder.Append("  border-color: #656565;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-background {");
            builder.Append("  background-color: white;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-2 {");
            builder.Append("  background-color: white;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-2-is-active {");
            builder.Append("  background-color: #ffe0e0;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-2-is-hoverable:hover {");
            builder.Append("  background-color: #ffe0e0;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-3 {");
            builder.Append("  background-color: #ffe0e0;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-3-is-active {");
            builder.Append("  background-color: #ffd4d4;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-3-is-hoverable:hover {");
            builder.Append("  background-color: #ffd4d4;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-3-background {");
            builder.Append("  background-color: white;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-4 {");
            builder.Append("  background-color: #fff2f2;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-5-is-active {");
            builder.Append("  background-color: #ffbdbd;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-5-is-hoverable:hover {");
            builder.Append("  background-color: #ffbdbd;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-6 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.3);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-1 {");
            builder.Append("  background-color: #FF0000;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-1-is-active {");
            builder.Append("  background-color: #ff1a1a;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-1-is-hoverable:hover {");
            builder.Append("  background-color: #ff1a1a;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-1-is-disabled {");
            builder.Append("  background-color: #ff3333;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-2 {");
            builder.Append("  background-color: #b30000;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-3 {");
            builder.Append("  background-color: #ff1a1a;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-4 {");
            builder.Append("  background-color: #ff6666;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-5 {");
            builder.Append("  background-color: #ff6666;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-5-is-hoverable:hover {");
            builder.Append("  background-color: #FF0000;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-6 {");
            builder.Append("  background-color: #940000;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-7 {");
            builder.Append("  background-color: #FF0000;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-8 {");
            builder.Append("  background-color: #FF0000;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-8-is-active-1 {");
            builder.Append("  background-color: #ff1a1a;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-8-is-active-2 {");
            builder.Append("  background-color: #ff1a1a;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #FFFFFF;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-9 {");
            builder.Append("  background-color: #ffb3b3;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-10 {");
            builder.Append("  background-color: #ff3333;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-11 {");
            builder.Append("  background-color: #ff1a1a;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-12 {");
            builder.Append("  background-color: #FF0000;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #ffffff;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-13 {");
            builder.Append("  background-color: #fff2f2;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 0, 0, 0.3);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-1 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #FF0000;");
            builder.Append("  border-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-2 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #b30000;");
            builder.Append("  border-color: #b30000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-3 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #ff1a1a;");
            builder.Append("  border-color: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-4 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #ff6666;");
            builder.Append("  border-color: #ff6666;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-5 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #ff6666;");
            builder.Append("  border-color: #ff6666;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-6 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #940000;");
            builder.Append("  border-color: #940000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-7 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #FF0000;");
            builder.Append("  border-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-8 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #FF0000;");
            builder.Append("  border-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-9 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #ffb3b3;");
            builder.Append("  border-color: #ffb3b3;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-10 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #ff3333;");
            builder.Append("  border-color: #ff3333;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-11 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #ff1a1a;");
            builder.Append("  border-color: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-primary-13 {");
            builder.Append("  background-color: #FFFFFF;");
            builder.Append("  color: #fff2f2;");
            builder.Append("  border-color: rgba(255, 0, 0, 0.3);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-1 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #dedede;");
            builder.Append("  border-color: #dedede;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-2 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #1a1a1a;");
            builder.Append("  border-color: #1a1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-3 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: rgba(0, 0, 0, 0.12);");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-4 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #595959;");
            builder.Append("  border-color: #595959;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-5 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #404040;");
            builder.Append("  border-color: #404040;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-6 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #c2c2c2;");
            builder.Append("  border-color: #c2c2c2;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-7 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #595959;");
            builder.Append("  border-color: #595959;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-8 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #dedede;");
            builder.Append("  border-color: #dedede;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-9 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #f0f0f0;");
            builder.Append("  border-color: #f0f0f0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-10 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #e0e0e0;");
            builder.Append("  border-color: #e0e0e0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-11 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #999999;");
            builder.Append("  border-color: #999999;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-12 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #4d4d4d;");
            builder.Append("  border-color: #4d4d4d;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-neutral-13 {");
            builder.Append("  background-color: transparent;");
            builder.Append("  color: #e6e6e6;");
            builder.Append("  border-color: #e6e6e6;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #FF0000;");
            builder.Append("  border-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-home-1 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #3f3f41;");
            builder.Append("  border-color: #3f3f41;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-away-1 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #9c9c9c;");
            builder.Append("  border-color: #9c9c9c;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-home-2 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #3f3f41;");
            builder.Append("  border-color: #940000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-away-2 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #9c9c9c;");
            builder.Append("  border-color: #940000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-home-3 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #3f3f41;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-away-3 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #9c9c9c;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-home-4 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #79797a;");
            builder.Append("  border-color: #79797a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-away-4 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #bababa;");
            builder.Append("  border-color: #bababa;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-home-5 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #29292a;");
            builder.Append("  border-color: #29292a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-away-5 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #656565;");
            builder.Append("  border-color: #656565;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary-1 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #FF0000;");
            builder.Append("  border-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary-2 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #b30000;");
            builder.Append("  border-color: #b30000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary-3 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #ff1a1a;");
            builder.Append("  border-color: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary-4 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #ff6666;");
            builder.Append("  border-color: #ff6666;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary-5 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #ff6666;");
            builder.Append("  border-color: #ff6666;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary-6 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #940000;");
            builder.Append("  border-color: #940000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary-7 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #FF0000;");
            builder.Append("  border-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary-8 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #FF0000;");
            builder.Append("  border-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary-9 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #ffb3b3;");
            builder.Append("  border-color: #ffb3b3;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary-10 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #ff3333;");
            builder.Append("  border-color: #ff3333;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-primary-11 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #ff1a1a;");
            builder.Append("  border-color: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-1 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #dedede;");
            builder.Append("  border-color: #dedede;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-2 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #1a1a1a;");
            builder.Append("  border-color: #1a1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-3 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: rgba(0, 0, 0, 0.12);");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-4 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #595959;");
            builder.Append("  border-color: #595959;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-5 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #404040;");
            builder.Append("  border-color: #404040;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-6 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #c2c2c2;");
            builder.Append("  border-color: #c2c2c2;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-7 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #595959;");
            builder.Append("  border-color: #595959;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-8 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #dedede;");
            builder.Append("  border-color: #dedede;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-9 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #f0f0f0;");
            builder.Append("  border-color: #f0f0f0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-10 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #e0e0e0;");
            builder.Append("  border-color: #e0e0e0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-11 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #999999;");
            builder.Append("  border-color: #999999;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-12 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #4d4d4d;");
            builder.Append("  border-color: #4d4d4d;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-base-1-is-active-neutral-13 {");
            builder.Append("  background-color: rgba(255, 0, 0, 0.12);");
            builder.Append("  color: #e6e6e6;");
            builder.Append("  border-color: #e6e6e6;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-home-1 {");
            builder.Append("  background-color: #3f3f41;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #3f3f41;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-away-1 {");
            builder.Append("  background-color: #9c9c9c;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: #9c9c9c;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-home-2 {");
            builder.Append("  background-color: #3f3f41;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #940000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-away-2 {");
            builder.Append("  background-color: #9c9c9c;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: #940000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-home-3 {");
            builder.Append("  background-color: #3f3f41;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #FFFFFF;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-away-3 {");
            builder.Append("  background-color: #9c9c9c;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: #FFFFFF;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-home-4 {");
            builder.Append("  background-color: #79797a;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #79797a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-away-4 {");
            builder.Append("  background-color: #bababa;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: #bababa;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-home-5 {");
            builder.Append("  background-color: #29292a;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #29292a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-away-5 {");
            builder.Append("  background-color: #656565;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: #656565;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-1 {");
            builder.Append("  background-color: #dedede;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-2 {");
            builder.Append("  background-color: #1a1a1a;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-3 {");
            builder.Append("  background-color: rgba(0, 0, 0, 0.12);");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-4 {");
            builder.Append("  background-color: #595959;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-5 {");
            builder.Append("  background-color: #404040;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-6 {");
            builder.Append("  background-color: #c2c2c2;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-7 {");
            builder.Append("  background-color: #595959;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-8 {");
            builder.Append("  background-color: #dedede;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-9 {");
            builder.Append("  background-color: #f0f0f0;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-10 {");
            builder.Append("  background-color: #e0e0e0;");
            builder.Append("  color: rgba(0, 0, 0, 0.82);");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-11 {");
            builder.Append("  background-color: #999999;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-12 {");
            builder.Append("  background-color: #4d4d4d;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-neutral-13 {");
            builder.Append("  background-color: #e6e6e6;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-win {");
            builder.Append("  background-color: red;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-draw {");
            builder.Append("  background-color: #c2c2c2;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-lose {");
            builder.Append("  background-color: #ff8787;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-text-secondary {");
            builder.Append("  opacity: 0.7;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-text-disabled {");
            builder.Append("  opacity: 0.35;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-text-tertiary {");
            builder.Append("  opacity: 0.54;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-1 .srt-text-secondary, .sr-bb .srt-primary-1.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-1-is-active .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-1-is-active.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-1-is-hoverable:hover .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-1-is-hoverable:hover.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-1-is-disabled .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-1-is-disabled.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-2 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-2.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-3 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-3.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-4 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-4.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-5 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-5.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-5-is-hoverable:hover .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-5-is-hoverable:hover.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-6 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-6.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-7 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-7.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-8 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-8.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-8-is-active-1 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-8-is-active-1.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-8-is-active-2 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-8-is-active-2.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-9 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-9.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-10 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-10.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-11 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-11.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-12 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-12.srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-13 .srt-text-secondary,");
            builder.Append(".sr-bb .srt-primary-13.srt-text-secondary {");
            builder.Append("  opacity: 0.8;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-1 .srt-text-disabled, .sr-bb .srt-primary-1.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-1-is-active .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-1-is-active.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-1-is-hoverable:hover .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-1-is-hoverable:hover.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-1-is-disabled .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-1-is-disabled.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-2 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-2.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-3 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-3.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-4 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-4.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-5 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-5.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-5-is-hoverable:hover .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-5-is-hoverable:hover.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-6 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-6.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-7 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-7.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-8 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-8.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-8-is-active-1 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-8-is-active-1.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-8-is-active-2 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-8-is-active-2.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-9 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-9.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-10 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-10.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-11 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-11.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-12 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-12.srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-13 .srt-text-disabled,");
            builder.Append(".sr-bb .srt-primary-13.srt-text-disabled {");
            builder.Append("  opacity: 0.6;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-primary-1 .srt-text-tertiary, .sr-bb .srt-primary-1.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-1-is-active .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-1-is-active.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-1-is-hoverable:hover .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-1-is-hoverable:hover.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-1-is-disabled .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-1-is-disabled.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-2 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-2.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-3 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-3.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-4 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-4.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-5 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-5.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-5-is-hoverable:hover .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-5-is-hoverable:hover.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-6 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-6.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-7 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-7.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-8 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-8.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-8-is-active-1 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-8-is-active-1.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-8-is-active-2 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-8-is-active-2.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-9 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-9.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-10 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-10.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-11 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-11.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-12 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-12.srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-13 .srt-text-tertiary,");
            builder.Append(".sr-bb .srt-primary-13.srt-text-tertiary {");
            builder.Append("  opacity: 0.7;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-icon {");
            builder.Append("  opacity: 0.33;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-icon-secondary {");
            builder.Append("  opacity: 0.7;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-elevation-1 {");
            builder.Append("  box-shadow: 0px 1px 2px 0px rgba(0, 0, 0, 0.2), 0px 1px 3px 0px rgba(0, 0, 0, 0.1);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-elevation-2 {");
            builder.Append("  box-shadow: 0px 3px 6px 0px rgba(0, 0, 0, 0.23), 0px 3px 6px 0px rgba(0, 0, 0, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-elevation-3 {");
            builder.Append("  box-shadow: 0px 6px 6px 0px rgba(0, 0, 0, 0.26), 0px 10px 20px 0px rgba(0, 0, 0, 0.19);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-elevation-center-2 {");
            builder.Append("  box-shadow: 0 1px 5px rgba(0, 0, 0, 0.23), 0 1px 5px rgba(0, 0, 0, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-inset-top-1 {");
            builder.Append("  box-shadow: inset 0 1px 2px 0 rgba(0, 0, 0, 0.23);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-inset-bottom-1 {");
            builder.Append("  box-shadow: inset 0 -1px 2px 0 rgba(0, 0, 0, 0.23);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-inset-top-2 {");
            builder.Append("  box-shadow: inset 0 3px 6px 0 rgba(0, 0, 0, 0.23);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-inset-bottom-2 {");
            builder.Append("  box-shadow: inset 0 -3px 6px 0 rgba(0, 0, 0, 0.23);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-inset-top-3 {");
            builder.Append("  box-shadow: inset 0 6px 6px 0 rgba(0, 0, 0, 0.23);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-inset-bottom-3 {");
            builder.Append("  box-shadow: inset 0 -6px 6px 0 rgba(0, 0, 0, 0.23);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-blue-card {");
            builder.Append("  fill: #2579ad;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-blue-card {");
            builder.Append("  stroke: #2579ad;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-yellow-card {");
            builder.Append("  fill: #ffbf00;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-yellow-card {");
            builder.Append("  stroke: #ffbf00;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-red-card {");
            builder.Append("  fill: #e43b3b;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-red-card {");
            builder.Append("  stroke: #e43b3b;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-substitution-in {");
            builder.Append("  stroke: #4fbe30;");
            builder.Append("  fill: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-substitution-in {");
            builder.Append("  fill: #4fbe30;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-substitution-out {");
            builder.Append("  stroke: #e43b3b;");
            builder.Append("  fill: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-substitution-out {");
            builder.Append("  fill: #e43b3b;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-own-goal {");
            builder.Append("  stroke: #e43b3b;");
            builder.Append("  fill: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-own-goal {");
            builder.Append("  fill: #e43b3b;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-relegation-1 {");
            builder.Append("  fill: #fdd835;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-relegation-1 {");
            builder.Append("  stroke: #fdd835;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-relegation-2 {");
            builder.Append("  fill: #ffb848;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-relegation-2 {");
            builder.Append("  stroke: #ffb848;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-relegation-3 {");
            builder.Append("  fill: #ef6c00;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-relegation-3 {");
            builder.Append("  stroke: #ef6c00;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-relegation-4 {");
            builder.Append("  fill: #e93a34;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-relegation-4 {");
            builder.Append("  stroke: #e93a34;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-relegation-5 {");
            builder.Append("  fill: #941d1d;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-relegation-5 {");
            builder.Append("  stroke: #941d1d;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-promotion-1 {");
            builder.Append("  fill: #51d151;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-promotion-1 {");
            builder.Append("  stroke: #51d151;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-promotion-2 {");
            builder.Append("  fill: #1b911b;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-promotion-2 {");
            builder.Append("  stroke: #1b911b;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-promotion-3 {");
            builder.Append("  fill: #0e8094;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-promotion-3 {");
            builder.Append("  stroke: #0e8094;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-promotion-4 {");
            builder.Append("  fill: #0a6cce;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-promotion-4 {");
            builder.Append("  stroke: #0a6cce;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-soccer-promotion-5 {");
            builder.Append("  fill: #4a9fe4;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-soccer-promotion-5 {");
            builder.Append("  stroke: #4a9fe4;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-nfl-timeout-1 {");
            builder.Append("  background-color: #f5a623;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-nfl-timeout-2 {");
            builder.Append("  background-color: rgba(245, 166, 35, 0.3);");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: rgba(255, 255, 255, 0.16);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-nfl-penalty {");
            builder.Append("  background-color: #f4a621;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #f4a621;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-nfl-negative-yards-1 {");
            builder.Append("  background-color: #ac182e;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #ac182e;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-nfl-negative-yards-2 {");
            builder.Append("  background-color: #ac182e;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #ac182e;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-nfl-first-line {");
            builder.Append("  background-color: #4b90de;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #4b90de;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-nfl-ten-line {");
            builder.Append("  background-color: #f5a623;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #f5a623;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-nfl-penalty {");
            builder.Append("  fill: #f4a621;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-nfl-penalty {");
            builder.Append("  stroke: #f4a621;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-nfl-negative-yards-1 {");
            builder.Append("  fill: #ac182e;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-nfl-negative-yards-1 {");
            builder.Append("  stroke: #ac182e;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-nfl-negative-yards-2 {");
            builder.Append("  fill: #ac182e;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-nfl-negative-yards-2 {");
            builder.Append("  stroke: #ac182e;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-nfl-first-line {");
            builder.Append("  fill: #4b90de;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-nfl-first-line {");
            builder.Append("  stroke: #4b90de;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-nfl-ten-line {");
            builder.Append("  fill: #f5a623;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-nfl-ten-line {");
            builder.Append("  stroke: #f5a623;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-mlb-run-1 {");
            builder.Append("  background-color: #009900;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #009900;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-mlb-run-2 {");
            builder.Append("  background-color: #ffffff;");
            builder.Append("  color: #009900;");
            builder.Append("  border-color: #009900;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-mlb-hit-1 {");
            builder.Append("  background-color: #f7ab11;");
            builder.Append("  color: #000000;");
            builder.Append("  border-color: #f7ab11;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-mlb-hit-2 {");
            builder.Append("  background-color: #ffffff;");
            builder.Append("  color: #f7ab11;");
            builder.Append("  border-color: #f7ab11;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-mlb-hit-3 {");
            builder.Append("  background-color: #00a4ff;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #00a4ff;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-mlb-error-1 {");
            builder.Append("  background-color: #d0021b;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #d0021b;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-mlb-error-2 {");
            builder.Append("  background-color: #ffffff;");
            builder.Append("  color: #d0021b;");
            builder.Append("  border-color: #d0021b;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-mlb-neutral-1 {");
            builder.Append("  background-color: #212121;");
            builder.Append("  color: #ffffff;");
            builder.Append("  border-color: #ffffff;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-mlb-base {");
            builder.Append("  fill: #00a4ff;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-strole-mlb-base {");
            builder.Append("  fill: #00a4ff;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-change-increase {");
            builder.Append("  fill: red;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-change-increase {");
            builder.Append("  stroke: red;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-change-decrease {");
            builder.Append("  fill: #ff8787;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-change-decrease {");
            builder.Append("  stroke: #ff8787;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-text {");
            builder.Append("  fill: #000000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-text-invert {");
            builder.Append("  fill: #ffffff;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-text-secondary {");
            builder.Append("  fill-opacity: 0.7;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-text-disabled {");
            builder.Append("  fill-opacity: 0.35;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-1 {");
            builder.Append("  fill: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-1 {");
            builder.Append("  stroke: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-1-active {");
            builder.Append("  fill: rgba(255, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-1-active {");
            builder.Append("  stroke: rgba(255, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-1-active-2 {");
            builder.Append("  fill: #e6e6e6;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-1-active-2 {");
            builder.Append("  stroke: #e6e6e6;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-1-primary {");
            builder.Append("  fill: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-1-primary {");
            builder.Append("  stroke: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-1-home {");
            builder.Append("  fill: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-1-home {");
            builder.Append("  stroke: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-1-away {");
            builder.Append("  fill: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-1-away {");
            builder.Append("  stroke: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-2 {");
            builder.Append("  fill: currentColor;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-2 {");
            builder.Append("  stroke: currentColor;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-2-active {");
            builder.Append("  fill: #ffe0e0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-2-active {");
            builder.Append("  stroke: #ffe0e0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-2-hover {");
            builder.Append("  fill: #ffe0e0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-2-hover {");
            builder.Append("  stroke: #ffe0e0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-3 {");
            builder.Append("  fill: #ffe0e0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-3 {");
            builder.Append("  stroke: #ffe0e0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-3-active {");
            builder.Append("  fill: #ffd4d4;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-3-active {");
            builder.Append("  stroke: #ffd4d4;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-base-3-hover {");
            builder.Append("  fill: #ffd4d4;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-base-3-hover {");
            builder.Append("  stroke: #ffd4d4;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-1 {");
            builder.Append("  fill: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-1 {");
            builder.Append("  stroke: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-2 {");
            builder.Append("  fill: #b30000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-2 {");
            builder.Append("  stroke: #b30000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-3 {");
            builder.Append("  fill: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-3 {");
            builder.Append("  stroke: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-4 {");
            builder.Append("  fill: #ff6666;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-4 {");
            builder.Append("  stroke: #ff6666;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-5 {");
            builder.Append("  fill: #ff6666;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-5 {");
            builder.Append("  stroke: #ff6666;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-6 {");
            builder.Append("  fill: #940000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-6 {");
            builder.Append("  stroke: #940000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-7 {");
            builder.Append("  fill: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-7 {");
            builder.Append("  stroke: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-8 {");
            builder.Append("  fill: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-8 {");
            builder.Append("  stroke: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-8-is-active-1 {");
            builder.Append("  fill: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-8-is-active-1 {");
            builder.Append("  stroke: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-8-is-active-2 {");
            builder.Append("  fill: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-8-is-active-2 {");
            builder.Append("  stroke: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-9 {");
            builder.Append("  fill: #ffb3b3;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-9 {");
            builder.Append("  stroke: #ffb3b3;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-10 {");
            builder.Append("  fill: #ff3333;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-10 {");
            builder.Append("  stroke: #ff3333;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-11 {");
            builder.Append("  fill: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-11 {");
            builder.Append("  stroke: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-primary-12 {");
            builder.Append("  fill: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-primary-12 {");
            builder.Append("  stroke: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-home-1 {");
            builder.Append("  fill: #3f3f41;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-home-1 {");
            builder.Append("  stroke: #3f3f41;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-home-2 {");
            builder.Append("  fill: #3f3f41;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-home-2 {");
            builder.Append("  stroke: #3f3f41;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-home-3 {");
            builder.Append("  fill: #3f3f41;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-home-3 {");
            builder.Append("  stroke: #3f3f41;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-home-4 {");
            builder.Append("  fill: #79797a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-home-4 {");
            builder.Append("  stroke: #79797a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-home-5 {");
            builder.Append("  fill: #29292a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-home-5 {");
            builder.Append("  stroke: #29292a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-away-1 {");
            builder.Append("  fill: #9c9c9c;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-away-1 {");
            builder.Append("  stroke: #9c9c9c;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-away-2 {");
            builder.Append("  fill: #9c9c9c;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-away-2 {");
            builder.Append("  stroke: #9c9c9c;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-away-3 {");
            builder.Append("  fill: #9c9c9c;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-away-3 {");
            builder.Append("  stroke: #9c9c9c;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-away-4 {");
            builder.Append("  fill: #bababa;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-away-4 {");
            builder.Append("  stroke: #bababa;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-away-5 {");
            builder.Append("  fill: #656565;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-away-5 {");
            builder.Append("  stroke: #656565;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-1 {");
            builder.Append("  fill: #dedede;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-1 {");
            builder.Append("  stroke: #dedede;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-2 {");
            builder.Append("  fill: #1a1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-2 {");
            builder.Append("  stroke: #1a1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-3 {");
            builder.Append("  fill: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-3 {");
            builder.Append("  stroke: rgba(0, 0, 0, 0.12);");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-4 {");
            builder.Append("  fill: #595959;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-4 {");
            builder.Append("  stroke: #595959;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-5 {");
            builder.Append("  fill: #404040;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-5 {");
            builder.Append("  stroke: #404040;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-6 {");
            builder.Append("  fill: #c2c2c2;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-6 {");
            builder.Append("  stroke: #c2c2c2;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-7 {");
            builder.Append("  fill: #595959;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-7 {");
            builder.Append("  stroke: #595959;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-8 {");
            builder.Append("  fill: #dedede;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-8 {");
            builder.Append("  stroke: #dedede;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-9 {");
            builder.Append("  fill: #f0f0f0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-9 {");
            builder.Append("  stroke: #f0f0f0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-10 {");
            builder.Append("  fill: #e0e0e0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-10 {");
            builder.Append("  stroke: #e0e0e0;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-11 {");
            builder.Append("  fill: #999999;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-11 {");
            builder.Append("  stroke: #999999;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-12 {");
            builder.Append("  fill: #4d4d4d;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-12 {");
            builder.Append("  stroke: #4d4d4d;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-13 {");
            builder.Append("  fill: #e6e6e6;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-13 {");
            builder.Append("  stroke: #e6e6e6;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-win {");
            builder.Append("  fill: red;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-win {");
            builder.Append("  stroke: red;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-draw {");
            builder.Append("  fill: #c2c2c2;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-draw {");
            builder.Append("  stroke: #c2c2c2;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-lose {");
            builder.Append("  fill: #ff8787;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-lose {");
            builder.Append("  stroke: #ff8787;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-base-1 {");
            builder.Append("  stop-color: transparent;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-1 {");
            builder.Append("  stop-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-2 {");
            builder.Append("  stop-color: #b30000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-3 {");
            builder.Append("  stop-color: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-4 {");
            builder.Append("  stop-color: #ff6666;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-5 {");
            builder.Append("  stop-color: #ff6666;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-6 {");
            builder.Append("  stop-color: #940000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-7 {");
            builder.Append("  stop-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-8 {");
            builder.Append("  stop-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-9 {");
            builder.Append("  stop-color: #ffb3b3;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-10 {");
            builder.Append("  stop-color: #ff3333;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-11 {");
            builder.Append("  stop-color: #ff1a1a;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-primary-12 {");
            builder.Append("  stop-color: #FF0000;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-home-1 {");
            builder.Append("  stop-color: #3f3f41;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stop-away-1 {");
            builder.Append("  stop-color: #9c9c9c;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-fill-neutral-14 {");
            builder.Append("  fill: #FFFFFF;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-stroke-neutral-14 {");
            builder.Append("  stroke: #FFFFFF;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-logo-powered-by-light {");
            builder.Append("  display: inline-block;");
            builder.Append("}");
            
            builder.Append(".sr-bb .srt-logo-powered-by-dark {");
            builder.Append("  display: none;");
            builder.Append("}");
            
            
            
            builder.Append("        </style>");
            builder.Append("    </head>");
            builder.Append("    <body style=\"background-color: #070915; padding: 0; margin: 0\">");
            builder.Append("        <script>");
            builder.Append("            (function(a,b,c,d,e,f,g,h,i){a[e]||(i=a[e]=function(){(a[e].q=a[e].q||[]).push(arguments)},i.l=1*new Date,i.o=f,");
            builder.Append("g=b.createElement(c),h=b.getElementsByTagName(c)[0],g.async=1,g.src=d,g.setAttribute(\"n\",e),h.parentNode.insertBefore(g,h)");

            return builder.ToString();
        }

        private static string BuildDynamicContent()
        {
            var builder = new StringBuilder();
            builder.Append(")})(window,document,\"script\", \"widget-url\", \"SIR\", {");
            builder.Append("    theme: false,");
            builder.Append("    language: 'input-language',");
            builder.Append("	matchId: 'input-match-id'");
            builder.Append("});");
            builder.Append("SIR(\"addWidget\", \".sr-widget\", \"match.lmtPlus\", { adsFrequency:false, scoreboard: \"disable\", detailedScoreboard: \"disable\", tabsPosition: \"disable\", matchId:input-match-id});");
            builder.Append("function waitForElement(id, callback){");
            builder.Append("    var waitInterval = setInterval(function(){");
            builder.Append("		var elements = document.getElementsByClassName(id);");
            builder.Append("        if(elements.length > 0){");
            builder.Append("            clearInterval(waitInterval);");
            builder.Append("            callback(elements);");
            builder.Append("        }");
            builder.Append("    }, 100);");
            builder.Append("}");
            builder.Append("waitForElement(\"sr-lmt-plus__footer-wrapper\", function(elements){");
            builder.Append("	for (i = 0; i < elements.length; i++) {");
            builder.Append("		elements[i].style.display = \"none\";");
            builder.Append("	}");
            builder.Append("});");
            builder.Append("        </script>");
            builder.Append("        <div class=\"widgets\">");
            builder.Append("            <div class=\"sr-widget\" data-sr-widget='match.lmtPlus' data-sr-match-id='input-match-id'></div>			");
            builder.Append("        </div>");
            builder.Append("    </body>");
            builder.Append("</html>");

            return builder.ToString();
        }
    }
}