// <auto-generated>
// Not implemented yet
// </auto-generated>
namespace LiveScore.Features.News.ViewModels
{
    using Core;
    using LiveScore.Core.ViewModels;
    using Prism.Navigation;

    public class EmptyNewsViewModel : ViewModelBase
    {
        public EmptyNewsViewModel(
            INavigationService navigationService,
            IDependencyResolver serviceLocator)
            : base(navigationService, serviceLocator)
        {
            Title = "News";
        }
        public override void OnDisappearing()
        {
            IsShowSportSelection = false;
        }
        public override void OnAppearing()
        {
            IsShowSportSelection = false;
        }
    }
}