// <auto-generated>
// Not implemented yet
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using LiveScore.Common;
using LiveScore.Common.Extensions;
using LiveScore.Common.LangResources;
using LiveScore.Core;
using LiveScore.Core.Models.Leagues;
using LiveScore.Core.Services;
using LiveScore.Core.ViewModels;
using LiveScore.Core.ViewModels.Leagues;
using Prism.Navigation;

namespace LiveScore.Features.League.ViewModels
{
    public class LeagueViewModel : ViewModelBase
    {
        public LeagueViewModel(
            INavigationService navigationService,
            IDependencyResolver serviceLocator,
            ILeagueService leagueService)
                : base(navigationService, serviceLocator)
        {
            Title = "League";
            this.leagueService = leagueService;
            buildFlagFunction = DependencyResolver.Resolve<Func<string, string>>(FuncNameConstants.BuildFlagUrlFuncName);
            LeagueGroups = new ObservableCollection<IGrouping<string, ViewModelBase>>();
        }

        private readonly ILeagueService leagueService;

        private readonly Func<string, string> buildFlagFunction;
        public ObservableCollection<IGrouping<string, ViewModelBase>> LeagueGroups { get; set; }

        public async Task BuildLeagueGroup()
        {
            var leagues = (await leagueService.GetMajorLeaguesAsync(CurrentLanguage))?.ToList();


            if(leagues != null)
            {
                BuildLeagueGroups(leagues);
            }

            IsBusy = false;
            HasData = IsNotBusy;
        }

        private void BuildLeagueGroups(List<ILeague> leagues)
        {

            var topLeagues = new ObservableCollection<ILeague>(leagues.OrderBy(league => league.Order).Take(10));

            var topLeagueGroup = BuildTopLeagueGroup(topLeagues);

            var countryLeagueGroup = BuildAllLeagueGroup(leagues);

            var leagueGroups = topLeagueGroup.Concat(countryLeagueGroup);

            LeagueGroups = new ObservableCollection<IGrouping<string, ViewModelBase>>(leagueGroups);
        }

        private IEnumerable<IGrouping<string, ViewModelBase>> BuildTopLeagueGroup(ObservableCollection<ILeague> topLeagues)
        {
            return topLeagues
                .Select(league => new LeagueItemViewModel(NavigationService, DependencyResolver, league, buildFlagFunction))
                .GroupBy(_ => AppResources.Popular);
        }

        private IEnumerable<IGrouping<string, ViewModelBase>> BuildAllLeagueGroup(IEnumerable<ILeague> leagues)
        {
            var orderedLeague = leagues
                .OrderBy(league => league.CountryName)
                .ThenBy(league => league.Name);

            var internationalLeagues = orderedLeague.Where(league => league.IsInternational);

            var allLeagueGroups = BuildInternationalLeaguesGroup(internationalLeagues);

            var countryLeagues = orderedLeague.Where(league => !league.IsInternational);
            var countryGroups = BuildCountryLeaguesGroup(countryLeagues);

            return allLeagueGroups.Concat(countryGroups);
        }
        private IEnumerable<IGrouping<string, ViewModelBase>> BuildInternationalLeaguesGroup(IEnumerable<ILeague> internationalLeagues)
        {
            var internationalCategory = new LeagueCategory
            {
                Name = AppResources.International
            };

            var internationalViewModels = new List<RegionGroupViewModel> 
            { 
                new RegionGroupViewModel(
                    NavigationService,
                    DependencyResolver,
                    internationalCategory,
                    internationalLeagues,
                    buildFlagFunction)
            };

            return internationalViewModels.GroupBy(_ => AppResources.AllLeagues);
        }


        private IEnumerable<IGrouping<string, ViewModelBase>> BuildCountryLeaguesGroup(IEnumerable<ILeague> countryLeagues)
        {
            var countryGroup = countryLeagues
                .GroupBy(league => new LeagueCategory
                {
                    CountryCode = league.CountryCode,
                    Name = league.CountryName
                })
                .ToDictionary(league 
                => league.Key);
            var countryLeaguesItems = new List<ViewModelBase>();
            foreach (var country in countryGroup.Keys)
            {
                countryLeaguesItems.Add(
                    new RegionGroupViewModel(
                        NavigationService, 
                        DependencyResolver,
                        country,
                        countryGroup[country],
                        buildFlagFunction)
                    );
            }

            return countryLeaguesItems.GroupBy( _ => AppResources.AllLeagues);
        }

        public override async void OnAppearing()
        {
            base.OnAppearing();
            await BuildLeagueGroup();
        }

    }
}