// <auto-generated>
// </auto-generated>
namespace LiveScore.Basketball.Services
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using LiveScore.Common.Extensions;
    using LiveScore.Core.Enumerations;
    using LiveScore.Core.Models.Matches;
    using LiveScore.Core.Models.Teams;
    using LiveScore.Core.Services;
    using Microsoft.AspNetCore.SignalR.Client;

    public class MatchService : IMatchService
    {
        public Task<IMatchOld> GetMatch(string matchId, Language language, bool forceFetchNewData = false)
        {
            throw new NotImplementedException();
        }

        public Task<IEnumerable<IMatch>> GetMatches(DateRange dateRange, Language language, bool forceFetchNewData = false)
        {
            throw new NotImplementedException();
        }

        public void SubscribeMatchEvent(HubConnection hubConnection, Action<byte, IMatchEvent> handler)
        {
            throw new NotImplementedException();
        }

        public void SubscribeTeamStatistic(HubConnection hubConnection, Action<byte, string, bool, ITeamStatistic> handler)
        {
            throw new NotImplementedException();
        }
    }
}