//// <auto-generated />
//using System;

//namespace LiveScore.Shared.Models.Dtos
//{



//    public class PlayerProfile
//    {
//        public DateTime generated_at { get; set; }
//        public string schema { get; set; }
//        public Player player { get; set; }
//        public Team1[] teams { get; set; }
//        public Role[] roles { get; set; }
//        public Statistics statistics { get; set; }
//    }

//    public class Player
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string first_name { get; set; }
//        public string last_name { get; set; }
//        public string type { get; set; }
//        public string date_of_birth { get; set; }
//        public string nationality { get; set; }
//        public string country_code { get; set; }
//        public int height { get; set; }
//        public int weight { get; set; }
//        public string preferred_foot { get; set; }
//        public string gender { get; set; }
//    }

//    public class Statistics
//    {
//        public Season[] seasons { get; set; }
//        public Totals totals { get; set; }
//    }

//    public class Totals
//    {
//        public int matches_played { get; set; }
//        public int substituted_in { get; set; }
//        public int substituted_out { get; set; }
//        public int goals_scored { get; set; }
//        public int assists { get; set; }
//        public int own_goals { get; set; }
//        public int yellow_cards { get; set; }
//        public int yellow_red_cards { get; set; }
//        public int red_cards { get; set; }
//        public DateTime last_event_time { get; set; }
//    }

//    public class Season
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public Statistics1 statistics { get; set; }
//        public Team team { get; set; }
//        public Tournaments tournament { get; set; }
//        public Season_Coverage_Info season_coverage_info { get; set; }
//    }

//    public class Statistics1
//    {
//        public int matches_played { get; set; }
//        public int substituted_in { get; set; }
//        public int substituted_out { get; set; }
//        public int goals_scored { get; set; }
//        public int assists { get; set; }
//        public int own_goals { get; set; }
//        public int yellow_cards { get; set; }
//        public int yellow_red_cards { get; set; }
//        public int red_cards { get; set; }
//        public DateTime last_event_time { get; set; }
//    }

//    public class Team
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country { get; set; }
//        public string country_code { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Tournaments
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public Sport sport { get; set; }
//        public Category category { get; set; }
//    }

//    public class Sport
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Category
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country_code { get; set; }
//    }

//    public class Season_Coverage_Info
//    {
//        public string season_id { get; set; }
//        public int scheduled { get; set; }
//        public int played { get; set; }
//        public string max_coverage_level { get; set; }
//        public int max_covered { get; set; }
//        public string min_coverage_level { get; set; }
//    }

//    public class Team1
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country { get; set; }
//        public string country_code { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Role
//    {
//        public string type { get; set; }
//        public string active { get; set; }
//        public Team2 team { get; set; }
//        public string start_date { get; set; }
//        public string end_date { get; set; }
//        public int jersey_number { get; set; }
//    }

//    public class Team2
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country { get; set; }
//        public string country_code { get; set; }
//        public string abbreviation { get; set; }
//    }

//}
