//// <auto-generated />
//using System;

//namespace LiveScore.Shared.Models.Dtos
//{


//    public class TeamSchedule
//    {
//        public DateTime generated_at { get; set; }
//        public string schema { get; set; }
//        public Team team { get; set; }
//        public Schedule[] schedule { get; set; }
//    }

//    public class Team
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country { get; set; }
//        public string country_code { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Schedule
//    {
//        public string id { get; set; }
//        public DateTime scheduled { get; set; }
//        public bool start_time_tbd { get; set; }
//        public string status { get; set; }
//        public Tournament_Round tournament_round { get; set; }
//        public Season season { get; set; }
//        public Tournaments tournament { get; set; }
//        public Competitor[] competitors { get; set; }
//        public Venue venue { get; set; }
//    }

//    public class Tournament_Round
//    {
//        public string type { get; set; }
//        public string name { get; set; }
//        public int cup_round_match_number { get; set; }
//        public int cup_round_matches { get; set; }
//        public string other_match_id { get; set; }
//        public string phase { get; set; }
//        public int number { get; set; }
//    }

//    public class Season
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string start_date { get; set; }
//        public string end_date { get; set; }
//        public string year { get; set; }
//        public string tournament_id { get; set; }
//    }

//    public class Tournaments
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public Sport sport { get; set; }
//        public Category category { get; set; }
//    }

//    public class Sport
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Category
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country_code { get; set; }
//    }

//    public class Venue
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public int capacity { get; set; }
//        public string city_name { get; set; }
//        public string country_name { get; set; }
//        public string map_coordinates { get; set; }
//        public string country_code { get; set; }
//    }

//    public class Competitor
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country { get; set; }
//        public string country_code { get; set; }
//        public string abbreviation { get; set; }
//        public string qualifier { get; set; }
//    }


//}
