//// <auto-generated />
//using System;

//namespace LiveScore.Shared.Models.Dtos
//{


//    public class TeamProfile
//    {
//        public DateTime generated_at { get; set; }
//        public string schema { get; set; }
//        public Team team { get; set; }
//        public Venue venue { get; set; }
//        public Jersey[] jerseys { get; set; }
//        public Manager manager { get; set; }
//        public Player[] players { get; set; }
//        public Statistics statistics { get; set; }
//    }

//    public class Team
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country { get; set; }
//        public string country_code { get; set; }
//        public Sport sport { get; set; }
//        public Category category { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Sport
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Category
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country_code { get; set; }
//    }

//    public class Venue
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public int capacity { get; set; }
//        public string city_name { get; set; }
//        public string country_name { get; set; }
//        public string map_coordinates { get; set; }
//        public string country_code { get; set; }
//    }

//    public class Manager
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string nationality { get; set; }
//        public string country_code { get; set; }
//    }

//    public class Statistics
//    {
//        public Season[] seasons { get; set; }
//    }

//    public class Season
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public Statistics1 statistics { get; set; }
//        public Tournaments tournament { get; set; }
//        public Form form { get; set; }
//    }

//    public class Statistics1
//    {
//        public int matches_played { get; set; }
//        public int matches_won { get; set; }
//        public int matches_drawn { get; set; }
//        public int matches_lost { get; set; }
//        public int goals_scored { get; set; }
//        public int goals_conceded { get; set; }
//        public int group_position { get; set; }
//        public int cup_rank { get; set; }
//        public string group_name { get; set; }
//    }

//    public class Tournaments
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public Sport1 sport { get; set; }
//        public Category1 category { get; set; }
//    }

//    public class Sport1
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Category1
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string country_code { get; set; }
//    }

//    public class Form
//    {
//        public string total { get; set; }
//        public string home { get; set; }
//        public string away { get; set; }
//    }

//    public class Jersey
//    {
//        public string type { get; set; }
//        public string _base { get; set; }
//        public string sleeve { get; set; }
//        public string number { get; set; }
//        public bool squares { get; set; }
//        public bool stripes { get; set; }
//        public bool horizontal_stripes { get; set; }
//        public bool split { get; set; }
//        public string shirt_type { get; set; }
//        public string sleeve_detail { get; set; }
//    }

//    public class Player
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string type { get; set; }
//        public string date_of_birth { get; set; }
//        public string nationality { get; set; }
//        public string country_code { get; set; }
//        public int height { get; set; }
//        public int weight { get; set; }
//        public int jersey_number { get; set; }
//        public string preferred_foot { get; set; }
//        public string gender { get; set; }
//    }


//}
