// <auto-generated />
using System;

namespace LiveScore.Shared.Models.Dtos
{


    public class Tournaments
    {
        public DateTime generated_at { get; set; }
        public string schema { get; set; }
        public Tournament[] tournaments { get; set; }
    }

    public class Tournament
    {
        public string id { get; set; }
        public string name { get; set; }
        public Sport sport { get; set; }
        public Category category { get; set; }
        public Current_Season current_season { get; set; }
        public Season_Coverage_Info season_coverage_info { get; set; }
    }

    public class Current_Season
    {
        public string id { get; set; }
        public string name { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string year { get; set; }
    }

    public class Season_Coverage_Info
    {
        public string season_id { get; set; }
        public int scheduled { get; set; }
        public int played { get; set; }
        public string max_coverage_level { get; set; }
        public int max_covered { get; set; }
        public string min_coverage_level { get; set; }
    }


}
