//// <auto-generated />
//using System;

//namespace LiveScore.Shared.Models.Dtos
//{


//    public class TournamentSeasons
//    {
//        public DateTime generated_at { get; set; }
//        public string schema { get; set; }
//        public Tournament tournament { get; set; }
//        public Season[] seasons { get; set; }
//    }

//    public class Tournament
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public Sport sport { get; set; }
//        public Category category { get; set; }
//    }

//    public class Sport
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Category
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Season
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string start_date { get; set; }
//        public string end_date { get; set; }
//        public string year { get; set; }
//        public string tournament_id { get; set; }
//    }


//}
