//// <auto-generated />
//using System;

//namespace LiveScore.Shared.Models.Dtos
//{


//    public class TournamentLeader
//    {
//        public DateTime generated_at { get; set; }
//        public string schema { get; set; }
//        public Tournament tournament { get; set; }
//        public Season_Coverage_Info season_coverage_info { get; set; }
//        public Top_Points[] top_points { get; set; }
//        public Top_Goals[] top_goals { get; set; }
//        public Top_Assists[] top_assists { get; set; }
//        public Top_Cards[] top_cards { get; set; }
//        public Top_Own_Goals[] top_own_goals { get; set; }
//        public Top_Clean_Sheets[] top_clean_sheets { get; set; }
//        public Top_Penalty_Goals[] top_penalty_goals { get; set; }
//        public Top_Shots_Faced_Saved[] top_shots_faced_saved { get; set; }
//        public Top_Shots_On_Goal[] top_shots_on_goal { get; set; }
//        public Top_Chances_Created[] top_chances_created { get; set; }
//        public Top_Successful_Passes[] top_successful_passes { get; set; }
//        public Top_Successful_Long_Passes[] top_successful_long_passes { get; set; }
//        public Top_Successful_Medium_Passes[] top_successful_medium_passes { get; set; }
//        public Top_Successful_Short_Passes[] top_successful_short_passes { get; set; }
//        public Top_Successful_Tackle_Duels[] top_successful_tackle_duels { get; set; }
//        public Top_Successful_Header_Duels[] top_successful_header_duels { get; set; }
//        public Top_Successful_Sprint_Duels[] top_successful_sprint_duels { get; set; }
//        public Top_Minutes_Played[] top_minutes_played { get; set; }
//        public Top_Average_Performance_Score[] top_average_performance_score { get; set; }
//    }

//    public class Tournament
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public Sport sport { get; set; }
//        public Category category { get; set; }
//        public Current_Season current_season { get; set; }
//    }

//    public class Sport
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Category
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Current_Season
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string start_date { get; set; }
//        public string end_date { get; set; }
//        public string year { get; set; }
//    }

//    public class Season_Coverage_Info
//    {
//        public string season_id { get; set; }
//        public int scheduled { get; set; }
//        public int played { get; set; }
//        public string max_coverage_level { get; set; }
//        public int max_covered { get; set; }
//        public string min_coverage_level { get; set; }
//    }

//    public class Top_Points
//    {
//        public int goals { get; set; }
//        public int assists { get; set; }
//        public int rank { get; set; }
//        public Player player { get; set; }
//        public Team team { get; set; }
//    }

//    public class Player
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Goals
//    {
//        public int goals { get; set; }
//        public int rank { get; set; }
//        public Player1 player { get; set; }
//        public Team1 team { get; set; }
//    }

//    public class Player1
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team1
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Assists
//    {
//        public int assists { get; set; }
//        public int rank { get; set; }
//        public Player2 player { get; set; }
//        public Team2 team { get; set; }
//    }

//    public class Player2
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team2
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Cards
//    {
//        public int red_cards { get; set; }
//        public int yellow_red_cards { get; set; }
//        public int yellow_cards { get; set; }
//        public int rank { get; set; }
//        public Player3 player { get; set; }
//        public Team3 team { get; set; }
//    }

//    public class Player3
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team3
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Own_Goals
//    {
//        public int own_goals { get; set; }
//        public int rank { get; set; }
//        public Player4 player { get; set; }
//        public Team4 team { get; set; }
//    }

//    public class Player4
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team4
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Clean_Sheets
//    {
//        public int clean_sheets { get; set; }
//        public int rank { get; set; }
//        public Player5 player { get; set; }
//        public Team5 team { get; set; }
//    }

//    public class Player5
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team5
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Penalty_Goals
//    {
//        public int penalty_goals { get; set; }
//        public int rank { get; set; }
//        public Player6 player { get; set; }
//        public Team6 team { get; set; }
//    }

//    public class Player6
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team6
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Shots_Faced_Saved
//    {
//        public int shots_faced_saved { get; set; }
//        public int percentage { get; set; }
//        public int rank { get; set; }
//        public Player7 player { get; set; }
//        public Team7 team { get; set; }
//    }

//    public class Player7
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team7
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Shots_On_Goal
//    {
//        public int shots_on_goal { get; set; }
//        public int rank { get; set; }
//        public Player8 player { get; set; }
//        public Team8 team { get; set; }
//    }

//    public class Player8
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team8
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Chances_Created
//    {
//        public int chances_created { get; set; }
//        public int rank { get; set; }
//        public Player9 player { get; set; }
//        public Team9 team { get; set; }
//    }

//    public class Player9
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team9
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Successful_Passes
//    {
//        public int successful_passes { get; set; }
//        public int percentage { get; set; }
//        public int rank { get; set; }
//        public Player10 player { get; set; }
//        public Team10 team { get; set; }
//    }

//    public class Player10
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team10
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Successful_Long_Passes
//    {
//        public int successful_long_passes { get; set; }
//        public int percentage { get; set; }
//        public int rank { get; set; }
//        public Player11 player { get; set; }
//        public Team11 team { get; set; }
//    }

//    public class Player11
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team11
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Successful_Medium_Passes
//    {
//        public int successful_medium_passes { get; set; }
//        public int percentage { get; set; }
//        public int rank { get; set; }
//        public Player12 player { get; set; }
//        public Team12 team { get; set; }
//    }

//    public class Player12
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team12
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Successful_Short_Passes
//    {
//        public int successful_short_passes { get; set; }
//        public int percentage { get; set; }
//        public int rank { get; set; }
//        public Player13 player { get; set; }
//        public Team13 team { get; set; }
//    }

//    public class Player13
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team13
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Successful_Tackle_Duels
//    {
//        public int successful_tackle_duels { get; set; }
//        public int percentage { get; set; }
//        public int rank { get; set; }
//        public Player14 player { get; set; }
//        public Team14 team { get; set; }
//    }

//    public class Player14
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team14
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Successful_Header_Duels
//    {
//        public int successful_header_duels { get; set; }
//        public int percentage { get; set; }
//        public int rank { get; set; }
//        public Player15 player { get; set; }
//        public Team15 team { get; set; }
//    }

//    public class Player15
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team15
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Successful_Sprint_Duels
//    {
//        public int successful_sprint_duels { get; set; }
//        public int percentage { get; set; }
//        public int rank { get; set; }
//        public Player16 player { get; set; }
//        public Team16 team { get; set; }
//    }

//    public class Player16
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team16
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Minutes_Played
//    {
//        public int minutes_played { get; set; }
//        public int rank { get; set; }
//        public Player17 player { get; set; }
//        public Team17 team { get; set; }
//    }

//    public class Player17
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team17
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }

//    public class Top_Average_Performance_Score
//    {
//        public float average_performance_score { get; set; }
//        public int rank { get; set; }
//        public Player18 player { get; set; }
//        public Team18 team { get; set; }
//    }

//    public class Player18
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//    }

//    public class Team18
//    {
//        public string id { get; set; }
//        public string name { get; set; }
//        public string abbreviation { get; set; }
//    }


//}
