//------------------------------------------------------------------------------
// <auto-generated> This file will be changed in the future
// </auto-generated>

namespace LiveScore.Core.ViewModels
{
    using System.Collections.ObjectModel;
    using System.Threading.Tasks;
    using Common.Extensions;
    using LiveScore.Core;
    using LiveScore.Core.Models;
    using LiveScore.Core.Services;
    using Prism.Navigation;

    public class SelectSportViewModel : ViewModelBase
    {
        private readonly ISportService sportService;
        private readonly ISettings settings;

        public SelectSportViewModel(
            INavigationService navigationService,
            IDependencyResolver dependencyResolver,
            ISportService sportService,
            ISettings settings)
                : base(navigationService, dependencyResolver)
        {
            this.sportService = sportService;
            SelectSportItemCommand = new DelegateAsyncCommand(OnSelectSportItem);
            DoneCommand = new DelegateAsyncCommand(OnDone);
            this.settings = settings ?? AppSettings.Current;
        }

        public SportItem SelectedSportItem { get; set; }

        public ObservableCollection<SportItem> SportItems { get; private set; }

        public DelegateAsyncCommand SelectSportItemCommand { get; }

        public DelegateAsyncCommand DoneCommand { get; }

        public override void Initialize(INavigationParameters parameters)
        {
            var sportItems = sportService.GetSportItems();

            foreach (var sportItem in sportItems)
            {
                sportItem.IsVisible = sportItem.Type.Value == CurrentSportId;
            }

            SportItems = new ObservableCollection<SportItem>(sportItems);
        }

        private async Task OnSelectSportItem()
        {
            if (SelectedSportItem.Type != null)
            {
                var isSportChanged = CurrentSportId != SelectedSportItem.Type.Value;

                settings.SportId = SelectedSportItem.Type.Value;

                if (isSportChanged)
                {
                    await NavigateToHome().ConfigureAwait(false);
                }
            }
        }

        private Task OnDone()
        {
            return NavigationService.GoBackAsync(useModalNavigation: true);
        }
    }
}