// <auto-generated> Can not be tested
// </auto-generated>
namespace LiveScore.Soccer.Services
{
    using LiveScore.Common.Configuration;
    using LiveScore.Core.Services;
    using Microsoft.AspNetCore.SignalR.Client;

    public class HubService : IHubService
    {
        private readonly IHubConnectionBuilder hubConnectionBuilder;
        private HubConnection matchHubConnection;

        public HubService(IHubConnectionBuilder hubConnectionBuilder)
        {
            this.hubConnectionBuilder = hubConnectionBuilder;
        }

        public HubConnection BuildMatchEventHubConnection()
        {
            return matchHubConnection ??
                (matchHubConnection = hubConnectionBuilder.WithUrl($"{Configuration.LocalHubEndPoint}/Soccer/MatchEventHub").Build());
        }
    }
}