// <auto-generated>
// </auto-generated>
namespace LiveScore.Soccer.Services
{
    using LiveScore.Common.Services;
    using LiveScore.Core.Models.Leagues;
    using LiveScore.Core.Services;
    using Refit;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public interface ISoccerLeagueApi
    {
        [Get("/League/GetLeagues?sportId={sportId}&language={languageCode}")]
        Task<IEnumerable<ILeague>> GetLeagues(string sportId, string languageCode);
    }

    public class LeagueService : BaseService, ILeagueService
    {
        public LeagueService(
            ISoccerLeagueApi leagueApi,
            ILoggingService loggingService,
            IApiPolicy apiPolicy) : base(loggingService)
        {

        }

        public async Task<IEnumerable<ILeague>> GetLeagues() => Enumerable.Empty<ILeague>();
    }
}