//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveScore.Common.LangResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveScore.Common.LangResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB.
        /// </summary>
        public static string AB {
            get {
                return ResourceManager.GetString("AB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned.
        /// </summary>
        public static string Abandoned {
            get {
                return ResourceManager.GetString("Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AET.
        /// </summary>
        public static string AET {
            get {
                return ResourceManager.GetString("AET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Extra Time.
        /// </summary>
        public static string AfterExtraTime {
            get {
                return ResourceManager.GetString("AfterExtraTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Penalties.
        /// </summary>
        public static string AfterPenalties {
            get {
                return ResourceManager.GetString("AfterPenalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP.
        /// </summary>
        public static string AP {
            get {
                return ResourceManager.GetString("AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian HDP.
        /// </summary>
        public static string AsianHDP {
            get {
                return ResourceManager.GetString("AsianHDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Await ET.
        /// </summary>
        public static string AwaitET {
            get {
                return ResourceManager.GetString("AwaitET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Extra Time.
        /// </summary>
        public static string AwaitExtraTime {
            get {
                return ResourceManager.GetString("AwaitExtraTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Await Pen.
        /// </summary>
        public static string AwaitPen {
            get {
                return ResourceManager.GetString("AwaitPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Penalties.
        /// </summary>
        public static string AwaitPenalties {
            get {
                return ResourceManager.GetString("AwaitPenalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string Away {
            get {
                return ResourceManager.GetString("Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ball possession.
        /// </summary>
        public static string BallPossession {
            get {
                return ResourceManager.GetString("BallPossession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked shots.
        /// </summary>
        public static string BlockedShots {
            get {
                return ResourceManager.GetString("BlockedShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmaker.
        /// </summary>
        public static string Bookmaker {
            get {
                return ResourceManager.GetString("Bookmaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canc.
        /// </summary>
        public static string Canc {
            get {
                return ResourceManager.GetString("Canc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network connection is lost. Please try again later..
        /// </summary>
        public static string ConnectionLostMessage {
            get {
                return ResourceManager.GetString("ConnectionLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the request timed out. Please refresh the page..
        /// </summary>
        public static string ConnectionTimeoutMessage {
            get {
                return ResourceManager.GetString("ConnectionTimeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner kicks.
        /// </summary>
        public static string CornerKicks {
            get {
                return ResourceManager.GetString("CornerKicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed.
        /// </summary>
        public static string Delayed {
            get {
                return ResourceManager.GetString("Delayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Channel.
        /// </summary>
        public static string EditChannel {
            get {
                return ResourceManager.GetString("EditChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETHT.
        /// </summary>
        public static string ETHT {
            get {
                return ResourceManager.GetString("ETHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Time Half Time.
        /// </summary>
        public static string ExtraTimeHalfTime {
            get {
                return ResourceManager.GetString("ExtraTimeHalfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fouls.
        /// </summary>
        public static string Fouls {
            get {
                return ResourceManager.GetString("Fouls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free kicks.
        /// </summary>
        public static string FreeKicks {
            get {
                return ResourceManager.GetString("FreeKicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FT.
        /// </summary>
        public static string FT {
            get {
                return ResourceManager.GetString("FT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Time.
        /// </summary>
        public static string FullTime {
            get {
                return ResourceManager.GetString("FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal kicks.
        /// </summary>
        public static string GoalKicks {
            get {
                return ResourceManager.GetString("GoalKicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Time.
        /// </summary>
        public static string HalfTime {
            get {
                return ResourceManager.GetString("HalfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT.
        /// </summary>
        public static string HT {
            get {
                return ResourceManager.GetString("HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT.
        /// </summary>
        public static string INT {
            get {
                return ResourceManager.GetString("INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupted.
        /// </summary>
        public static string Interrupted {
            get {
                return ResourceManager.GetString("Interrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leagues.
        /// </summary>
        public static string Leagues {
            get {
                return ResourceManager.GetString("Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Odds.
        /// </summary>
        public static string LiveOdds {
            get {
                return ResourceManager.GetString("LiveOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        public static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nations.
        /// </summary>
        public static string Nations {
            get {
                return ResourceManager.GetString("Nations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data yet ....
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no games available.
        /// </summary>
        public static string NoGames {
            get {
                return ResourceManager.GetString("NoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        public static string OddsTypeDecimal {
            get {
                return ResourceManager.GetString("OddsTypeDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offside.
        /// </summary>
        public static string Offside {
            get {
                return ResourceManager.GetString("Offside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1X2.
        /// </summary>
        public static string OneXTwo {
            get {
                return ResourceManager.GetString("OneXTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Odds.
        /// </summary>
        public static string OpeningOdds {
            get {
                return ResourceManager.GetString("OpeningOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over/Under.
        /// </summary>
        public static string OverUnder {
            get {
                return ResourceManager.GetString("OverUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen.
        /// </summary>
        public static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalties.
        /// </summary>
        public static string Penalties {
            get {
                return ResourceManager.GetString("Penalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty Shoot-Out.
        /// </summary>
        public static string PenaltyShootOut {
            get {
                return ResourceManager.GetString("PenaltyShootOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postp.
        /// </summary>
        public static string Postp {
            get {
                return ResourceManager.GetString("Postp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postponed.
        /// </summary>
        public static string Postponed {
            get {
                return ResourceManager.GetString("Postponed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red cards.
        /// </summary>
        public static string RedCards {
            get {
                return ResourceManager.GetString("RedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        public static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Leg, Aggregate Score:.
        /// </summary>
        public static string SecondLeg {
            get {
                return ResourceManager.GetString("SecondLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shots off target.
        /// </summary>
        public static string ShotsOffTarget {
            get {
                return ResourceManager.GetString("ShotsOffTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shots on target.
        /// </summary>
        public static string ShotsOnTarget {
            get {
                return ResourceManager.GetString("ShotsOnTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Delayed.
        /// </summary>
        public static string StartDelayed {
            get {
                return ResourceManager.GetString("StartDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw-ins.
        /// </summary>
        public static string ThrowIns {
            get {
                return ResourceManager.GetString("ThrowIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total shots.
        /// </summary>
        public static string TotalShots {
            get {
                return ResourceManager.GetString("TotalShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        public static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Schedule.
        /// </summary>
        public static string TVSchedule {
            get {
                return ResourceManager.GetString("TVSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under.
        /// </summary>
        public static string Under {
            get {
                return ResourceManager.GetString("Under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World News.
        /// </summary>
        public static string WorldNews {
            get {
                return ResourceManager.GetString("WorldNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards.
        /// </summary>
        public static string YellowCards {
            get {
                return ResourceManager.GetString("YellowCards", resourceCulture);
            }
        }
    }
}
