//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveScore.Common.LangResources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LiveScore.Common.LangResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        public static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        public static string Leagues {
            get {
                return ResourceManager.GetString("Leagues", resourceCulture);
            }
        }
        
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        public static string TVSchedule {
            get {
                return ResourceManager.GetString("TVSchedule", resourceCulture);
            }
        }
        
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        public static string FT {
            get {
                return ResourceManager.GetString("FT", resourceCulture);
            }
        }
        
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        public static string EditChannel {
            get {
                return ResourceManager.GetString("EditChannel", resourceCulture);
            }
        }
        
        public static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        public static string Nations {
            get {
                return ResourceManager.GetString("Nations", resourceCulture);
            }
        }
        
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        public static string Transfers {
            get {
                return ResourceManager.GetString("Transfers", resourceCulture);
            }
        }
        
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        public static string WorldNews {
            get {
                return ResourceManager.GetString("WorldNews", resourceCulture);
            }
        }
        
        public static string Postp {
            get {
                return ResourceManager.GetString("Postp", resourceCulture);
            }
        }
        
        public static string StartDelay {
            get {
                return ResourceManager.GetString("StartDelay", resourceCulture);
            }
        }
        
        public static string Delayed {
            get {
                return ResourceManager.GetString("Delayed", resourceCulture);
            }
        }
        
        public static string Canc {
            get {
                return ResourceManager.GetString("Canc", resourceCulture);
            }
        }
        
        public static string INT {
            get {
                return ResourceManager.GetString("INT", resourceCulture);
            }
        }
        
        public static string HT {
            get {
                return ResourceManager.GetString("HT", resourceCulture);
            }
        }
        
        public static string AB {
            get {
                return ResourceManager.GetString("AB", resourceCulture);
            }
        }
        
        public static string AET {
            get {
                return ResourceManager.GetString("AET", resourceCulture);
            }
        }
        
        public static string AP {
            get {
                return ResourceManager.GetString("AP", resourceCulture);
            }
        }
        
        public static string AwaitPen {
            get {
                return ResourceManager.GetString("AwaitPen", resourceCulture);
            }
        }
        
        public static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
    }
}
